import Head from "next/head";
import Layout from "../components/layout";
import { useFetchPosts } from "./blog/controllers/use-fetch-posts";

export default function About() {
  const [{ data, isLoading }] = useFetchPosts();
  return (
    <>
      <Head>
        <title>androobay | about</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section>
          {isLoading && <div>Loading...</div>}
          {!isLoading && (
            <>
              <h1>About</h1>
              <p>This is my website</p>
              {data.name}
            </>
          )}
        </section>
      </Layout>
    </>
  );
}
