import Head from "next/head";
import Layout from "../components/layout";

export default function Contact() {
  return (
    <>
      <Head>
        <title>androobay | contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section>
          <h1>Contact</h1>
          <p>This is my website</p>
        </section>
      </Layout>
    </>
  );
}
